/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/avisos-incubacion`; params?: Router.UnknownInputParams; } | { pathname: `/enfermedades`; params?: Router.UnknownInputParams; } | { pathname: `/lotes`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/nueva-incubacion`; params?: Router.UnknownInputParams; } | { pathname: `/nuevo-lote`; params?: Router.UnknownInputParams; } | { pathname: `/registrar-evento`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/avisos-incubacion`; params?: Router.UnknownOutputParams; } | { pathname: `/enfermedades`; params?: Router.UnknownOutputParams; } | { pathname: `/lotes`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/nueva-incubacion`; params?: Router.UnknownOutputParams; } | { pathname: `/nuevo-lote`; params?: Router.UnknownOutputParams; } | { pathname: `/registrar-evento`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/avisos-incubacion${`?${string}` | `#${string}` | ''}` | `/enfermedades${`?${string}` | `#${string}` | ''}` | `/lotes${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/nueva-incubacion${`?${string}` | `#${string}` | ''}` | `/nuevo-lote${`?${string}` | `#${string}` | ''}` | `/registrar-evento${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/avisos-incubacion`; params?: Router.UnknownInputParams; } | { pathname: `/enfermedades`; params?: Router.UnknownInputParams; } | { pathname: `/lotes`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/nueva-incubacion`; params?: Router.UnknownInputParams; } | { pathname: `/nuevo-lote`; params?: Router.UnknownInputParams; } | { pathname: `/registrar-evento`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
